In [1]:
import numpy as np

path = "/workspace/code/camera_calibration/calibration_parameters.npz"

with np.load(path) as data:
    camera_matrix = data["camera_matrix"]
    dist_coeffs = data["dist_coeffs"]
    image_size = tuple(data["image_size"])  

In [3]:
data.keys()

KeysView(NpzFile 'object' with keys: camera_matrix, dist_coeffs, rvecs, tvecs, image_size)

In [4]:
print("Camera Matrix:\n", camera_matrix)
print("Distortion Coefficients:\n", dist_coeffs)
print("Image Size:", image_size)    

Camera Matrix:
 [[1.67514300e+03 0.00000000e+00 8.80968039e+02]
 [0.00000000e+00 1.28634860e+03 1.02593966e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[ 0.20856113 -0.02898647  0.02729207 -0.09730363  0.00345747]]
Image Size: (3840, 2160)
