In [4]:
import numpy as np

path = "/workspace/code/camera_calibration/calibration_parameters.npz"

with np.load(path) as data:
    camera_matrix = data["camera_matrix"]
    dist_coeffs = data["dist_coeffs"]
    image_size = tuple(data["image_size"])  

In [5]:
data.keys()

KeysView(NpzFile 'object' with keys: camera_matrix, dist_coeffs, rvecs, tvecs, image_size...)

In [6]:
print("Camera Matrix:\n", camera_matrix)
print("Distortion Coefficients:\n", dist_coeffs)
print("Image Size:", image_size)    

Camera Matrix:
 [[1.10308405e+03 0.00000000e+00 9.47946068e+02]
 [0.00000000e+00 1.10601861e+03 5.31242592e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[ 0.17697328 -0.45675065 -0.0026601  -0.00330938  0.35538705]]
Image Size: (1920, 1080)
